### ISSUE TITLE
Latest Release Update?

### ISSUE THREAD

**Issue by samyak-jn** [kostaskougios/cloning#99]
Hi,

Thanks for developing the `cloning` tool. Various other Java packages are using the cloning tool.
I intend to package `cloning` for the Debian and its derivatives.

However, as per the release section, the latest release is wayyy older (2012). It will be great If you can add a new release to the package.

Thank you very much! :D

**Comment by kostaskougios** [comment]
Hi, there has been several releases after that, there must have been a couple even this year. Which "release section" are you referring to?

**Comment by samyak-jn** [comment]
Hi,

It shows the last release was on March 15, 2012.

![image](https://user-images.githubusercontent.com/44315191/84033852-239fb580-a9b7-11ea-926b-65c5f9466c73.png)

**Comment by kostaskougios** [comment]
Oh, that's because since then it is released to maven central. Can you grab the latest release from here?

https://search.maven.org/search?q=g:%22io.github.kostaskougios%22%20AND%20a:%22cloning%22

If you click the release number (1.10.3) it will take you to it and then click the "Browse" folder on top-right. It will take you here:

https://repo1.maven.org/maven2/io/github/kostaskougios/cloning/1.10.3/

How do you normally include a deb package for java jars, where do you download the jar from?

**Comment by samyak-jn** [comment]
That's the case, We don't include the jar files or any other pre-built binaries directly! 
The jar files are built from the package itself. We have Gradle and maven in Debian to produce those binaries for us.

I intend to package your source code, by extracting the repository tarballs (.tar.gz).

**Comment by samyak-jn** [comment]
As correctly as I checked, I found two different tar files.
`cloning-1.10.3-dist.tar.gz` and `cloning-1.10.3-project.tar.gz`.

Can you please explain me the difference between them?

**Comment by samyak-jn** [comment]
Hii, nevermind I checked it.

Thanks for the help and the tool of course! :D
